"""The KUKA LBR iiwa 7 R800 and 14 R820 models, against KUKA's published numbers.

Both are generated by ``external/convert/build_lbr_iiwa_mjcf.py`` from lbr-stack's description
packages. What earns a test here is what a regenerated model could get wrong without failing to
load:

- the published figures -- arm mass, axis torques and speeds, position limits, reach -- which every
  constant below is taken from, never measured from the model, so no test is tautological;
- the kinematics, checked against a product-of-exponentials chain built from the datasheet's
  link lengths alone, which shares nothing with the MJCF's body tree (MuJoCo Menagerie's
  independently derived iiwa 14 agrees with this model to 1e-15 m);
- the arm battery of the robot-porting skill, run through ``spawn_arm`` and the manifest's
  ``arm_controller`` as a world runs it: gravity hold, joint-limit sweep, payload, speed limits;
- the ROS 2 interface, which is lbr_fri_ros2_stack's so a client written for the real arm drives
  this one unchanged.
"""

from __future__ import annotations

import xml.etree.ElementTree as ET
from pathlib import Path

import mujoco
import numpy as np
import pytest

from roqsim.config import load_config_from_dict
from roqsim.engine import Engine
from roqsim.models import apply_assets, resolve_model

JOINTS = [f"A{i}" for i in range(1, 8)]

#: Position limits, shared by both variants (KUKA; lbr-stack config/joint_limits.yaml agrees), deg.
LIMITS_DEG = [170, 120, 170, 120, 170, 120, 175]

#: Published per variant. Mass: KUKA's arm weight. Torque / speed: KUKA's axis tables, as Drake's
#: iiwa_description/README.md records them with their sources. Lengths: base->A2, A2->A4, A4->A6,
#: A6->flange, the datasheet geometry. Reach: KUKA's, which is A2->A6 (shoulder to wrist centre).
VARIANTS = {
    "lbr_iiwa7": {
        "mass": 23.9,
        "torque": [176, 176, 110, 110, 110, 40, 40],
        "speed_deg": [98, 98, 100, 130, 140, 180, 180],
        "lengths": [0.340, 0.400, 0.400, 0.126],
        "reach": 0.800,
        "payload": 7.0,
    },
    "lbr_iiwa14": {
        "mass": 29.9,
        "torque": [320, 320, 176, 176, 110, 40, 40],
        "speed_deg": [85, 85, 100, 75, 130, 135, 135],
        "lengths": [0.360, 0.420, 0.400, 0.126],
        "reach": 0.820,
        "payload": 14.0,
    },
}

PREFIX = "iiwa_"
variants = pytest.mark.parametrize("name", sorted(VARIANTS))


def _model(name: str) -> mujoco.MjModel:
    asset = resolve_model(f"roqsim_manipulation_assets:{name}")
    spec = mujoco.MjSpec.from_file(str(asset.path))
    apply_assets(spec, asset)
    return spec.compile()


def _engine(name: str, timestep: float = 0.002) -> Engine:
    world = {
        "sim": {"timestep": timestep},
        "components": [{"spawn_arm": {"model": name, "prefix": PREFIX}, "name": "iiwa"}],
    }
    engine = Engine(load_config_from_dict(world, base_dir=Path(".")), preview=True)
    engine.setup()
    engine.reset()
    return engine


def _qadr(model: mujoco.MjModel, prefix: str = "") -> list[int]:
    return [
        int(model.jnt_qposadr[mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_JOINT, prefix + j)])
        for j in JOINTS
    ]


def _poe_flange(lengths: list[float], q: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    """Flange pose from the datasheet geometry alone (space-frame product of exponentials).

    At the zero pose the iiwa stands straight up: A1, A3, A5, A7 on the vertical axis, A2, A4, A6
    horizontal at the shoulder, elbow and wrist heights, A4 turning the opposite way to A2 and A6.
    """
    d1, d3, d5, d7 = lengths
    z, y = np.array([0.0, 0.0, 1.0]), np.array([0.0, 1.0, 0.0])
    axes = [(z, 0.0), (y, d1), (z, 0.0), (-y, d1 + d3), (z, 0.0), (y, d1 + d3 + d5), (z, 0.0)]

    def exp(w: np.ndarray, height: float, theta: float) -> np.ndarray:
        k = np.array([[0, -w[2], w[1]], [w[2], 0, -w[0]], [-w[1], w[0], 0]])
        r = np.eye(3) + np.sin(theta) * k + (1 - np.cos(theta)) * k @ k
        p = np.array([0.0, 0.0, height])
        t = np.eye(4)
        t[:3, :3], t[:3, 3] = r, p - r @ p  # rotation about an axis through p
        return t

    pose = np.eye(4)
    for (w, h), theta in zip(axes, q, strict=True):
        pose = pose @ exp(w, h, theta)
    home = np.eye(4)
    home[2, 3] = d1 + d3 + d5 + d7
    pose = pose @ home
    return pose[:3, 3], pose[:3, :3]


@variants
def test_mass_is_kukas(name):
    assert _model(name).body_mass.sum() == pytest.approx(VARIANTS[name]["mass"], abs=1e-3)


@variants
def test_joint_limits_are_kukas(name):
    model = _model(name)
    for joint, deg in zip(JOINTS, LIMITS_DEG, strict=True):
        jid = mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_JOINT, joint)
        assert model.jnt_range[jid] == pytest.approx(np.radians([-deg, deg]), abs=1e-5), joint


@variants
def test_actuator_torque_is_the_datasheets(name):
    # Not the description's `effort`, which is a uniform 200 placeholder on every axis.
    model = _model(name)
    for joint, torque in zip(JOINTS, VARIANTS[name]["torque"], strict=True):
        aid = mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_ACTUATOR, joint)
        assert model.actuator_forcelimited[aid]
        assert model.actuator_forcerange[aid] == pytest.approx([-torque, torque]), joint


@variants
def test_forward_kinematics_match_the_datasheet_geometry(name):
    model = _model(name)
    data = mujoco.MjData(model)
    site = mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_SITE, "attachment_site")
    assert site >= 0, "attachment_site is what a tool welds to; it must exist"
    rng = np.random.default_rng(0)
    for _ in range(300):
        q = rng.uniform(model.jnt_range[:, 0], model.jnt_range[:, 1])
        data.qpos[:] = q
        mujoco.mj_kinematics(model, data)
        pos, rot = _poe_flange(VARIANTS[name]["lengths"], q)
        assert data.site_xpos[site] == pytest.approx(pos, abs=1e-9)
        assert data.site_xmat[site].reshape(3, 3) == pytest.approx(rot, abs=1e-9)


@variants
def test_reach_is_kukas(name):
    """KUKA's reach is the wrist centre's distance from the A1 axis, arm stretched out horizontally.

    The wrist centre (where A5, A6 and A7 meet) is found from the flange, 0.126 m back along its
    axis; the joint anchors would not do, since the description places each body origin beside its
    axis rather than on it.
    """
    model = _model(name)
    data = mujoco.MjData(model)
    data.qpos[:] = [0.0, np.pi / 2, 0.0, 0.0, 0.0, 0.0, 0.0]
    mujoco.mj_kinematics(model, data)
    site = mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_SITE, "attachment_site")
    d1, *_, d7 = VARIANTS[name]["lengths"]
    wrist = data.site_xpos[site] - d7 * data.site_xmat[site].reshape(3, 3)[:, 2]
    assert np.hypot(*wrist[:2]) == pytest.approx(VARIANTS[name]["reach"], abs=1e-6)
    assert wrist[2] == pytest.approx(d1, abs=1e-6)


@variants
def test_no_option_block_and_base_at_origin(name):
    # Integrator, timestep and contact settings belong to the world's `sim:` block; spawn_arm places
    # the arm, so a baked base offset would double up with the world's. Parsed rather than grepped:
    # the header comment says "<option>".
    asset = resolve_model(f"roqsim_manipulation_assets:{name}")
    assert ET.parse(asset.path).getroot().find("option") is None
    model = _model(name)
    assert model.body_pos[mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_BODY, "link_0")] == (
        pytest.approx(np.zeros(3))
    )


@variants
def test_ros_interface_is_lbr_stacks(name):
    engine = _engine(name)
    try:
        endpoints = {e.name: e for e in engine.ctx.interface.all() if e.owner == "iiwa"}
        assert {e.namespace for e in endpoints.values()} == {"lbr"}
        ros = {k: e.backend.get("ros2", {}) for k, e in endpoints.items()}
        assert "joint_states" in endpoints  # /lbr/joint_states
        assert ros["follow_joint_trajectory"]["name"] == (
            "joint_trajectory_controller/follow_joint_trajectory"
        )
        assert ros["joint_command"]["topic"] == "joint_trajectory_controller/joint_trajectory"
        assert ros["controller_state"]["topic"] == "joint_trajectory_controller/controller_state"
        names, *_ = engine.ctx.blackboard.get("arm:iiwa").read_state()
        assert list(names) == [f"lbr_{j}" for j in JOINTS]
    finally:
        engine.shutdown()


@variants
def test_gravity_hold(name):
    """E1: at home and stretched out horizontally (the worst case for A2), the arm must not sag."""
    engine = _engine(name)
    try:
        arm = engine.ctx.blackboard.get("arm:iiwa")
        data, qadr = engine.ctx.data, _qadr(engine.ctx.model, PREFIX)
        for target in (None, [0.0, np.pi / 2, 0.0, 0.0, 0.0, 0.0, 0.0]):
            if target is not None:
                arm.set_targets(arm.joint_names, target)
                for _ in range(1500):
                    engine.step()
            start = data.qpos[qadr].copy()
            for _ in range(1500):
                engine.step()
            drift = np.degrees(np.abs(data.qpos[qadr] - start)).max()
            assert drift < 0.05, f"arm sagged {drift:.3f} deg under gravity at {target}"
    finally:
        engine.shutdown()


@variants
def test_joint_limit_sweep(name):
    """E2: commanded past each limit, every joint stops at KUKA's limit."""
    engine = _engine(name)
    try:
        arm = engine.ctx.blackboard.get("arm:iiwa")
        data, qadr = engine.ctx.data, _qadr(engine.ctx.model, PREFIX)
        for sign in (1.0, -1.0):
            # A4 is bent the other way so the stretched arm does not fold into itself.
            target = [sign * np.radians(d + 20) for d in LIMITS_DEG]
            target[3] = -target[3]
            arm.set_targets(arm.joint_names, target)
            for _ in range(3500):
                engine.step()
            reached = np.degrees(np.abs(data.qpos[qadr]))
            assert reached == pytest.approx(LIMITS_DEG, abs=0.5), f"sign {sign}: {reached}"
    finally:
        engine.shutdown()


@variants
def test_rated_payload_held_stretched_out(name):
    """E4: the rated payload at the flange, arm horizontal, held without saturating an axis.

    The payload is a downward force at the flange (``xfrc_applied``) rather than a welded body, so
    that spawn_arm's gravity compensation cannot carry it: the actuators must.
    """
    engine = _engine(name)
    try:
        arm = engine.ctx.blackboard.get("arm:iiwa")
        model, data = engine.ctx.model, engine.ctx.data
        qadr = _qadr(model, PREFIX)
        target = [0.0, np.pi / 2, 0.0, 0.0, 0.0, 0.0, 0.0]
        arm.set_targets(arm.joint_names, target)
        for _ in range(1500):
            engine.step()
        body = mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_BODY, PREFIX + "link_7")
        site = mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_SITE, PREFIX + "attachment_site")
        force = np.array([0.0, 0.0, -VARIANTS[name]["payload"] * 9.81])
        peak = np.zeros(model.nu)
        for _ in range(1500):
            data.xfrc_applied[body] = 0
            # A force at the flange is that force plus its moment about the body's centre of mass.
            lever = data.site_xpos[site] - data.xipos[body]
            data.xfrc_applied[body, :3] = force
            data.xfrc_applied[body, 3:] = np.cross(lever, force)
            engine.step()
            peak = np.maximum(peak, np.abs(data.actuator_force))
        sag = np.degrees(np.abs(data.qpos[qadr] - target)).max()
        assert sag < 1.0, f"rated payload sags the arm {sag:.2f} deg"
        assert (peak < model.actuator_forcerange[:, 1] * 0.999).all(), f"saturated: {peak}"
    finally:
        engine.shutdown()


@variants
def test_axes_move_no_faster_than_kukas_speeds(name):
    """A step to a far pose is limited to the datasheet speeds by the manifest's max_velocity."""
    engine = _engine(name)
    try:
        arm = engine.ctx.blackboard.get("arm:iiwa")
        data, qadr = engine.ctx.data, _qadr(engine.ctx.model, PREFIX)
        model = engine.ctx.model
        dofs = [
            int(model.jnt_dofadr[mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_JOINT, PREFIX + j)])
            for j in JOINTS
        ]
        target = [1.5, -0.5, 1.0, -1.5, 1.0, 1.5, 2.0]
        arm.set_targets(arm.joint_names, target)
        peak = np.zeros(7)
        for _ in range(4000):
            engine.step()
            peak = np.maximum(peak, np.abs(data.qvel[dofs]))
        speed = np.radians(VARIANTS[name]["speed_deg"])
        assert (np.degrees(peak) <= np.degrees(speed) * 1.05).all(), np.degrees(peak)
        assert data.qpos[qadr] == pytest.approx(target, abs=np.radians(0.1))
    finally:
        engine.shutdown()


@variants
def test_self_collision_rate(name):
    """The hulls of lbr-stack's collision meshes must not make the arm more conservative than the
    package's reference arms (~17.5% of uniformly sampled configurations for ur5e / ur10e)."""
    model = _model(name)
    data = mujoco.MjData(model)
    rng = np.random.default_rng(1)
    trials, colliding = 1500, 0
    for _ in range(trials):
        data.qpos[:] = rng.uniform(model.jnt_range[:, 0], model.jnt_range[:, 1])
        mujoco.mj_forward(model, data)
        colliding += any(data.contact[c].dist < -1e-4 for c in range(data.ncon))
    assert colliding / trials < 0.22, f"self-collision on {colliding / trials:.1%} of random poses"


#: The drive test's poses, rad. Each moves several axes at once and stays inside every limit.
POSES = [
    [0.0, 0.5236, 0.0, -1.0472, 0.0, 1.0472, 0.0],
    [0.7854, 0.7854, 0.0, -0.7854, 0.0, 0.7854, 0.7854],
    [-0.7854, 0.3491, 0.5236, -1.5708, -0.5236, 0.5236, -0.7854],
    [0.0, -0.5236, 0.0, 1.0472, 0.0, -0.5236, 1.5708],
]


@variants
def test_drive_through_poses_over_the_trajectory_endpoint(name):
    """The drive test: the trajectory endpoint a ROS 2 FollowJointTrajectory goal arrives at, named
    as lbr-stack names the joints, takes the arm through four poses, and ``joint_states`` reports it
    there.

    Speed is checked twice, because two different things bound it. The controller's reference --
    the held target ``controller_state`` reports -- must move no faster than KUKA's axis speeds,
    exactly: that is the manifest's ``max_velocity``. The joint itself tracks that reference with a
    servo, and while the shoulder accelerates hard the inertial coupling makes a distal axis
    overshoot it briefly (measured: up to 11% on the iiwa 14's A4 in the last move); that is bounded
    loosely, to catch a servo that has gone underdamped rather than to grade it.
    """
    engine = _engine(name)
    try:
        eps = {e.name: e for e in engine.ctx.interface.all() if e.owner == "iiwa"}
        names = [f"lbr_{j}" for j in JOINTS]
        speed = np.radians(VARIANTS[name]["speed_deg"])
        dt = engine.ctx.model.opt.timestep
        for pose in POSES:
            eps["follow_joint_trajectory"].write({"names": names, "positions": pose})
            reference = np.array(eps["controller_state"].read().reference.positions)
            peak_ref, peak = np.zeros(7), np.zeros(7)
            for _ in range(2000):  # 4 s: the longest move here needs ~2.1 s at the datasheet speeds
                engine.step()
                now = np.array(eps["controller_state"].read().reference.positions)
                peak_ref = np.maximum(peak_ref, np.abs(now - reference) / dt)
                reference = now
                state = eps["joint_states"].read()
                peak = np.maximum(peak, np.abs(state.velocities))
            assert list(state.names) == names
            assert np.degrees(np.abs(np.subtract(state.positions, pose))).max() < 0.1, pose
            assert (peak_ref <= speed * (1 + 1e-4)).all(), f"reference {np.degrees(peak_ref)} deg/s"
            assert (peak <= speed * 1.15).all(), f"joints {np.degrees(peak)} deg/s at {pose}"
    finally:
        engine.shutdown()
