"""The MoveIt SRDF export: the semantics come from arguments, the collision matrix is computed.

The matrix is the part worth testing. It is generated by sampling random configurations in MuJoCo (the
Setup Assistant's own algorithm), and the consequences of getting it wrong are asymmetric and both bad:

* a **missing** ``Adjacent``/``Always`` entry leaves MoveIt checking a pair that is in collision in every
  reachable state, so every plan is rejected and the arm simply never moves;
* a **wrongly disabled** pair hides a real self-collision.

Neither shows up as an error, which is why these are behavioural tests over a real composed robot rather
than assertions about the file's shape.
"""

from __future__ import annotations

import xml.etree.ElementTree as ET

import mujoco
import pytest

from roqsim.config import load_config_from_dict
from roqsim.engine import Engine
from roqsim.export_srdf import (
    ArmGroup,
    base_free_joint,
    build_srdf,
    collision_matrix,
    exported_root_bodies,
    exported_root_body,
    links_from_urdf,
    resolve_base_joint,
    unmask_self_collision,
)
from roqsim.export_urdf import UrdfExporter

# ---------------------------------------------------------------------------------------------
# A synthetic three-link chain, so each matrix category can be provoked deliberately.
#
#   link_a  at the origin
#   link_b  a metre away, touching nothing
#   link_c  child of b but positioned back ON TOP of link_a
#   link_far  out of reach of everything
#   link_ghost  visual-only geometry, so it cannot collide by construction
#
# So (a,b) and (b,c) are Adjacent, (a,c) is Always (grandparent/grandchild is NOT parent-filtered by
# MuJoCo, so real contacts appear), and everything involving link_far or link_ghost is Never. Joint
# ranges are deliberately tiny (in RADIANS, see the compiler tag): the links must not be able to move
# apart, or these become sometimes-collides. A joint with hi <= lo is treated as unlimited instead.
# ---------------------------------------------------------------------------------------------
CHAIN = """
<mujoco>
  <!-- angle="radian" explicitly: MuJoCo's compiler defaults to DEGREES, so the joint ranges below
       would otherwise be read as +-0.01 deg. That bites silently -- a sampler over a range 57x too
       small never separates anything, and every pair comes back "Always". -->
  <compiler angle="radian"/>
  <worldbody>
    <body name="link_a">
      <joint name="j_a" type="hinge" axis="0 0 1" range="-0.01 0.01"/>
      <geom name="g_a" type="box" size="0.1 0.1 0.1" mass="1"/>
      <body name="link_b" pos="1 0 0">
        <joint name="j_b" type="hinge" axis="0 0 1" range="-0.01 0.01"/>
        <geom name="g_b" type="box" size="0.1 0.1 0.1" mass="1"/>
        <body name="link_c" pos="-0.95 0 0">
          <joint name="j_c" type="hinge" axis="0 0 1" range="-0.01 0.01"/>
          <geom name="g_c" type="box" size="0.1 0.1 0.1" mass="1"/>
        </body>
      </body>
    </body>
    <body name="link_far" pos="8 0 0">
      <geom name="g_far" type="box" size="0.1 0.1 0.1" mass="1"/>
    </body>
    <body name="link_ghost" pos="0 0 0.02">
      <geom name="g_ghost" type="box" size="0.3 0.3 0.3" mass="1" contype="0" conaffinity="0"/>
    </body>
  </worldbody>
</mujoco>
"""


@pytest.fixture(scope="module")
def chain():
    model = mujoco.MjModel.from_xml_string(CHAIN)
    names = ("link_a", "link_b", "link_c", "link_far", "link_ghost")
    links = {int(mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_BODY, n)): n for n in names}
    # 200 samples, not the 10000 default: the ranges here are tiny, so the verdicts do not depend on
    # sample count, and the point of the test is the classification rather than statistical confidence.
    matrix = collision_matrix(model, links, samples=200)
    return model, links, {(a, b): reason for a, b, reason in matrix}


def _reason(matrix: dict, a: str, b: str) -> str | None:
    return matrix.get((a, b)) or matrix.get((b, a))


def test_joined_links_are_adjacent(chain):
    """Links sharing a joint always touch at their axis, and no planner can avoid it."""
    _model, _links, matrix = chain
    assert _reason(matrix, "link_a", "link_b") == "Adjacent"
    assert _reason(matrix, "link_b", "link_c") == "Adjacent"


def test_permanently_overlapping_links_are_always(chain):
    """A pair in collision in every sampled state must be disabled, or nothing ever plans.

    link_c is positioned inside link_a and only its grandparent joint can move it, which is not enough
    to separate them. `Always` rather than `Adjacent` because they are not joined to each other.
    """
    _model, _links, matrix = chain
    assert _reason(matrix, "link_a", "link_c") == "Always"


def test_links_that_never_touch_are_never(chain):
    """The category that makes checking affordable, and the one that is a sampling argument."""
    _model, _links, matrix = chain
    for other in ("link_a", "link_b", "link_c"):
        assert _reason(matrix, other, "link_far") == "Never"


def test_visual_only_geometry_can_never_collide(chain):
    """A link carrying no collision geometry lands in Never as a consequence, not a special case.

    link_ghost is a 0.6 m box straddling link_a, so a version of this that ignored contype/conaffinity
    would classify it Always instead.
    """
    _model, _links, matrix = chain
    assert _reason(matrix, "link_a", "link_ghost") == "Never"


def test_a_sometimes_colliding_pair_is_left_for_moveit_to_check():
    """Neither Never nor Always: MoveIt must keep checking it, so it must NOT appear in the matrix.

    A 1 m bar on a hinge sweeping past a small block: measured, it collides in 62 of 400 sampled
    configurations. Disabling that pair would hide a real self-collision; keeping it costs a check.
    """
    model = mujoco.MjModel.from_xml_string(
        """
        <mujoco>
          <compiler angle="radian"/>
          <worldbody>
            <body name="link_a">
              <joint name="j_a" type="hinge" axis="0 0 1" range="-3.14 3.14"/>
              <geom name="g_a" type="box" size="0.5 0.05 0.05" mass="1"/>
            </body>
            <body name="link_b" pos="0.45 0 0">
              <geom name="g_b" type="box" size="0.05 0.05 0.05" mass="1"/>
            </body>
          </worldbody>
        </mujoco>
        """
    )
    links = {
        int(mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_BODY, n)): n for n in ("link_a", "link_b")
    }
    matrix = {(a, b): r for a, b, r in collision_matrix(model, links, samples=400)}
    assert _reason(matrix, "link_a", "link_b") is None, (
        "a bar that sweeps through a block in SOME configurations was disabled; that hides a real "
        "self-collision"
    )


def test_matrix_is_computed_even_when_the_model_masks_self_collision():
    """A model that cannot self-collide must still get a real matrix, not one that disables everything.

    Robot models here routinely mask self-collision off on purpose (`contype=2 / conaffinity=1` on every
    collision geom) because the vendor's collision primitives of neighbouring links overlap at rest.
    Under that mask MuJoCo reports no contacts between robot links at all, so a sampler that trusted it
    would mark every pair `Never` and ship an SRDF with MoveIt's self-collision checking switched off
    entirely. Measured on the TIAGo Pro before this was fixed: 0 contacts over 200 poses, 1711 `Never`,
    0 `Always`.

    The question the matrix asks is geometric, so the sampler enables collision itself — and must put the
    model back afterwards, since the caller goes on to simulate with it.
    """
    # EVERY collision geom masked, which is what a real port does: `contype=2 / conaffinity=1` on the
    # whole robot means no two of its geoms can ever collide with each other. The visual-only
    # link_ghost keeps 0/0 and must stay uncollidable.
    masked = CHAIN
    for geom in ("g_a", "g_b", "g_c", "g_far"):
        masked = masked.replace(
            f'<geom name="{geom}" type="box" size="0.1 0.1 0.1" mass="1"/>',
            f'<geom name="{geom}" type="box" size="0.1 0.1 0.1" mass="1" '
            f'contype="2" conaffinity="1"/>',
        )
    names = ("link_a", "link_b", "link_c", "link_far", "link_ghost")

    # As loaded, nothing can collide. This is the state that produced the meaningless matrix.
    model = mujoco.MjModel.from_xml_string(masked)
    links = {int(mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_BODY, n)): n for n in names}
    data = mujoco.MjData(model)
    mujoco.mj_kinematics(model, data)
    mujoco.mj_collision(model, data)
    assert data.ncon == 0, "fixture is wrong: these geoms should be masked apart as loaded"

    # Sampling it must REFUSE rather than return a matrix that disables everything.
    with pytest.raises(ValueError, match="masked apart"):
        collision_matrix(model, links, samples=50)

    # Clearing the mask on the compiled model does NOT work -- MuJoCo fixes what can collide at compile
    # time. Pinned because it is the trap that makes the fix look unnecessary.
    for g in range(model.ngeom):
        model.geom_contype[g] = 1
        model.geom_conaffinity[g] = 1
    mujoco.mj_kinematics(model, data)
    mujoco.mj_collision(model, data)
    assert data.ncon == 0, (
        "clearing the mask post-compile now works; simplify unmask_self_collision"
    )

    # On the SPEC, before compiling, it does.
    spec = mujoco.MjSpec.from_string(masked)
    assert unmask_self_collision(spec) > 0
    unmasked = spec.compile()
    links = {int(mujoco.mj_name2id(unmasked, mujoco.mjtObj.mjOBJ_BODY, n)): n for n in names}
    matrix = {(a, b): r for a, b, r in collision_matrix(unmasked, links, samples=200)}
    assert _reason(matrix, "link_a", "link_c") == "Always"
    # ...and a link that is only visual stays uncollidable, so it is still Never.
    assert _reason(matrix, "link_a", "link_ghost") == "Never"


# ---------------------------------------------------------------------------------------------
# The SRDF document itself, and the collapsed-gripper mapping.
# ---------------------------------------------------------------------------------------------
def _composed(tmp_path):
    """Husky + UR10e + a Robotiq 2F-85 — a real closed-loop gripper, which is the interesting case."""
    return load_config_from_dict(
        {
            "sim": {},
            "plugins": [
                {
                    "spawn_robot": {
                        "model": "husky_a200",
                        "pose": {"position": {"x": 0.0, "y": 0.0}},
                    },
                    "name": "husky",
                },
                {
                    "spawn_arm": {
                        "model": "ur10e",
                        "prefix": "ur10e_",
                        "mount": {"robot": "husky", "body": "base_link"},
                        "pos": [0.25, 0.0, 0.2587],
                        "end_effector": {
                            "model": "robotiq_2f85",
                            "replaces": ["ee_plate"],
                        },
                    },
                    "name": "arm",
                },
            ],
        },
        base_dir=tmp_path,
    )


@pytest.fixture(scope="module")
def collapsed(tmp_path_factory):
    """The composed robot exported with the gripper collapsed into one link, as MoveIt needs it."""
    tmp_path = tmp_path_factory.mktemp("collapsed")
    engine = Engine(_composed(tmp_path))
    engine.setup()
    model = engine.ctx.model
    urdf = tmp_path / "robot.urdf"
    UrdfExporter(
        model,
        prefix="ur10e_",
        name="test_robot",
        root_link="arm_base_link",
        mesh_dir=tmp_path / "meshes",
        collapse=("base_mount",),
    ).export().write(urdf, encoding="utf-8", xml_declaration=True)
    yield model, urdf
    engine.shutdown()


@pytest.fixture(scope="module")
def bolted(tmp_path_factory):
    """The same arm BOLTED DOWN — `spawn_arm` with no `mount:`, i.e. a static pedestal cell."""
    tmp_path = tmp_path_factory.mktemp("bolted")
    config = load_config_from_dict(
        {
            "sim": {},
            "plugins": [
                {
                    "spawn_arm": {
                        "model": "ur5e",
                        "prefix": "ur5e_",
                        "pos": [0.0, 0.0, 0.30],
                        "pedestal": True,
                    },
                    "name": "ur5e",
                }
            ],
        },
        base_dir=tmp_path,
    )
    engine = Engine(config)
    engine.setup()
    model = engine.ctx.model
    urdf = tmp_path / "robot.urdf"
    UrdfExporter(
        model,
        prefix="ur5e_",
        name="test_arm",
        mesh_dir=tmp_path / "meshes",
    ).export().write(urdf, encoding="utf-8", xml_declaration=True)
    yield model, urdf
    engine.shutdown()


def test_the_renamed_root_link_is_in_the_matrix(collapsed):
    """`--root-link` renames the root body, and the matrix must still cover that link.

    A Menagerie arm's root body is `base`; the URDF calls it `base_link` (or whatever --root-link
    says), so matching bodies to link names by name alone leaves the root unmapped -- and a link absent
    from the matrix is a link MoveIt keeps checking. Root and first link touch at their shared axis in
    every state, so the missing `Adjacent` entry is the expensive kind.
    """
    model, urdf = collapsed
    links = links_from_urdf(model, urdf, strip="ur10e_")
    assert "arm_base_link" in links.values(), "the renamed root link is not in the matrix at all"
    assert links[exported_root_body(model, links)] == "arm_base_link"
    matrix = {(a, b): r for a, b, r in collision_matrix(model, links, samples=50)}
    assert _reason(matrix, "arm_base_link", "shoulder_link") == "Adjacent"


def test_a_mounted_arm_rides_the_base_free_joint(collapsed):
    """The arm is welded to a Husky, and the Husky floats: that is a planar virtual joint."""
    model, urdf = collapsed
    links = links_from_urdf(model, urdf, strip="ur10e_")
    # The free joint belongs to the BASE, which is not part of the exported URDF -- so the walk has to
    # leave the exported subtree to find it.
    assert base_free_joint(model, links) is not None
    assert resolve_base_joint(model, links)[0] == "planar"


def test_a_bolted_down_arm_gets_no_virtual_joint(bolted):
    """The regression this exists for: a pedestal arm must not be handed a virtual joint.

    Nothing publishes odom -> base_link in a static cell, so move_group logs "The complete state of the
    robot is not yet known. Missing virtual_joint" once a second and never assembles a complete robot
    state. It does not fail outright -- a driver that pins start states still gets answers -- it just
    mostly times out. Measured on the Kwee UR5e cell: 7/28 queries solved with the joint, 28/28 without.
    """
    model, urdf = bolted
    links = links_from_urdf(model, urdf, strip="ur5e_")
    assert base_free_joint(model, links) is None
    assert resolve_base_joint(model, links)[0] == "fixed"

    tree = build_srdf(
        model,
        links,
        name="test_arm",
        arm_base="base_link",
        arm_tip="wrist_3_link",
        gripper_joint="robotiq_85_left_knuckle_joint",
        gripper_open=0.0,
        gripper_close=0.8,
        home={},
        samples=50,
    )
    assert tree.getroot().find("virtual_joint") is None


def test_declaring_a_virtual_joint_on_a_bolted_down_arm_is_refused(bolted):
    """Explicitly asking for the broken file must fail, not be honoured quietly.

    Suppressing a virtual joint is only ever a degraded planning frame; declaring one nothing publishes
    breaks the robot state, so the two directions are not symmetric and only one is refused.
    """
    model, urdf = bolted
    links = links_from_urdf(model, urdf, strip="ur5e_")
    for requested in ("planar", "floating"):
        with pytest.raises(ValueError, match="Missing virtual_joint"):
            resolve_base_joint(model, links, requested)


# A rail carriage in miniature: the root body slides, and its child is the arm's first link. Both
# bodies are one tree, as any exported URDF is.
RAIL = """
<mujoco>
  <compiler angle="radian"/>
  <worldbody>
    <body name="carriage">
      <joint name="rail" type="slide" axis="1 0 0" range="0 2"/>
      <geom name="g_carriage" type="box" size="0.1 0.1 0.1" mass="1"/>
      <body name="link_1" pos="0 0 0.2">
        <joint name="j_1" type="hinge" axis="0 0 1"/>
        <geom name="g_1" type="box" size="0.1 0.1 0.1" mass="1"/>
      </body>
    </body>
  </worldbody>
</mujoco>
"""


def _ids(model, *names) -> dict[int, str]:
    return {int(mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_BODY, n)): n for n in names}


def test_a_jointed_root_is_not_a_floating_base():
    """A hinge or slide above the root is a real URDF joint, not a base whose pose lives in TF.

    `roqsim export urdf` emits such a root below a synthetic fixed `world` link, so MoveIt already has the
    fixed root it requires. Only a MuJoCo FREE joint means the base's pose comes from TF.
    """
    model = mujoco.MjModel.from_xml_string(RAIL)
    links = _ids(model, "carriage", "link_1")
    assert base_free_joint(model, links) is None
    assert resolve_base_joint(model, links)[0] == "fixed"

    floating = mujoco.MjModel.from_xml_string(
        RAIL.replace('<joint name="rail" type="slide" axis="1 0 0" range="0 2"/>', "<freejoint/>")
    )
    # An unnamed free joint still has to be reported as one, since the verdict hinges on its existence.
    assert base_free_joint(floating, _ids(floating, "carriage", "link_1")) is not None
    assert resolve_base_joint(floating, _ids(floating, "carriage", "link_1"))[0] == "planar"


def test_links_reaching_outside_the_robot_are_rejected():
    """Two roots means `links` covers more than one tree, and every base verdict would be arbitrary.

    It is a real mistake, not a hypothetical: `--strip` that matches too little leaves a URDF link name
    matching a body in some other subtree of the world.
    """
    model = mujoco.MjModel.from_xml_string(CHAIN)
    links = _ids(model, "link_a", "link_b", "link_far")  # link_far is its own tree
    with pytest.raises(ValueError, match="exactly one root link"):
        exported_root_body(model, links)


def test_collapsed_gripper_members_map_to_the_collapsed_link(collapsed):
    """Every body folded into a collapsed link must be ATTRIBUTED to that link in the matrix.

    This is what makes the matrix agree with the URDF rather than with the MJCF. A 2F-85's thirteen
    linkage bodies become one ``base_mount`` link whose ``<collision>`` carries all of their geometry,
    so MoveIt checks *that link* against the wrist — and if the sampler only ever attributed the
    collapse ROOT's own geoms, the finger geometry's verdicts would be missing entirely. Missing means
    "keep checking", so a finger that overlaps the wrist in every state would block every plan, with no
    error anywhere to explain it.
    """
    model, urdf = collapsed
    links = links_from_urdf(model, urdf, strip="ur10e_")
    urdf_links = {link.get("name") for link in ET.parse(urdf).getroot().findall("link")}
    assert "base_mount" in urdf_links
    # The linkage bodies are gone from the URDF...
    assert "robotiq_85_base_link" not in urdf_links
    # ...so their MuJoCo bodies must resolve to the link that swallowed them.
    for body_name in (
        "ur10e_robotiq_85_base_link",
        "ur10e_left_pad",
        "ur10e_right_silicone_pad",
    ):
        bid = int(mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_BODY, body_name))
        assert bid > 0, f"{body_name} is not in this model"
        assert links.get(bid) == "base_mount", (
            f"{body_name} maps to {links.get(bid)!r}; its geometry is part of the base_mount link in "
            "the URDF, so its contacts must be attributed there"
        )


def test_bodies_outside_the_robot_are_not_mapped(collapsed):
    """Walking up to a parent link must not drag in the world's own bodies.

    The husky is in this model too and is not part of the exported arm; a mapping that reached for "the
    nearest ancestor with a link" without checking would attribute chassis contacts to the arm.
    """
    model, urdf = collapsed
    links = links_from_urdf(model, urdf, strip="ur10e_")
    for body_name in ("husky_base_link", "husky_front_left_wheel_link"):
        bid = mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_BODY, body_name)
        if bid > 0:
            assert bid not in links, f"{body_name} was mapped to {links.get(bid)!r}"


def test_srdf_declares_the_groups_states_and_virtual_joint(collapsed):
    """The semantic half: what a human chose, spelled the way MoveIt expects to read it."""
    model, urdf = collapsed
    links = links_from_urdf(model, urdf, strip="ur10e_")
    tree = build_srdf(
        model,
        links,
        name="test_robot",
        arm_base="arm_base_link",
        arm_tip="wrist_3_link",
        gripper_joint="robotiq_85_left_knuckle_joint",
        gripper_open=0.0,
        gripper_close=0.8,
        home={"shoulder_pan_joint": 0.0},
        samples=50,
    )
    root = tree.getroot()
    assert root.get("name") == "test_robot"
    # This arm rides a Husky, so the base floats: its pose is TF, not a planning variable. The child
    # link must be the URDF's ROOT (renamed by --root-link) -- srdfdom skips a virtual joint whose
    # child is any other link, which degrades exactly like declaring none.
    vj = root.find("virtual_joint")
    assert vj is not None and vj.get("type") == "planar" and vj.get("parent_frame") == "odom"
    assert vj.get("child_link") == "arm_base_link"
    chain = root.find("group[@name='arm']/chain")
    assert chain.get("base_link") == "arm_base_link" and chain.get("tip_link") == "wrist_3_link"
    ee = root.find("end_effector")
    assert ee.get("group") == "gripper" and ee.get("parent_link") == "wrist_3_link"
    states = {gs.get("name") for gs in root.findall("group_state")}
    assert {"open", "closed", "home"} <= states
    # The gripper's named states must be in the JOINT's units, so a MoveIt named target and a
    # GripperCommand mean the same number.
    closed = root.find("group_state[@name='closed']/joint")
    assert float(closed.get("value")) == pytest.approx(0.8)


def test_srdf_is_parseable_xml(collapsed, tmp_path):
    """Guards the generator's own warning: ElementTree writes `--` inside a comment without complaint,
    and then neither it nor MoveIt can read the file back."""
    model, urdf = collapsed
    links = links_from_urdf(model, urdf, strip="ur10e_")
    out = tmp_path / "robot.srdf"
    build_srdf(
        model,
        links,
        name="test_robot",
        arm_base="arm_base_link",
        arm_tip="wrist_3_link",
        gripper_joint="robotiq_85_left_knuckle_joint",
        gripper_open=0.0,
        gripper_close=0.8,
        home={},
        samples=50,
    ).write(out, encoding="utf-8", xml_declaration=True)
    reparsed = ET.parse(out).getroot()  # raises if the comment or any attribute is malformed
    assert reparsed.tag == "robot"


# -- several robots in one description -----------------------------------------------------------
#
# A dual-arm cell is one description with two trees. The checks that guard a single robot must
# generalise rather than be dropped: they are what catches `links` reaching into the wrong subtree,
# and that mistake does not get less likely with two robots in the file.

_TWO_ARMS = """
<mujoco>
  <compiler angle="radian"/>
  <worldbody>
    <body name="a_base" pos="0 -0.4 0">
      <geom name="a_g" type="box" size="0.1 0.1 0.1" mass="1"/>
      <body name="a_link" pos="0 0 0.2">
        <joint name="a_j" type="hinge" axis="0 0 1" range="-3 3"/>
        <geom name="a_g2" type="box" size="0.05 0.5 0.05" mass="1"/>
      </body>
    </body>
    <body name="b_base" pos="0 0.4 0">
      <geom name="b_g" type="box" size="0.1 0.1 0.1" mass="1"/>
      <body name="b_link" pos="0 0 0.2">
        <joint name="b_j" type="hinge" axis="0 0 1" range="-3 3"/>
        <geom name="b_g2" type="box" size="0.05 0.5 0.05" mass="1"/>
      </body>
    </body>
  </worldbody>
</mujoco>
"""


@pytest.fixture(scope="module")
def two_arms():
    model = mujoco.MjModel.from_xml_string(_TWO_ARMS)
    return model, _ids(model, "a_base", "a_link", "b_base", "b_link")


def test_two_robots_have_two_roots_and_that_is_asked_for_explicitly(two_arms):
    """The count is an argument, not an assumption: it is what still catches a link name matching a
    body in some other subtree, which is the mistake the single-root check exists for."""
    model, links = two_arms
    assert [links[b] for b in exported_root_bodies(model, links, 2)] == ["a_base", "b_base"]
    with pytest.raises(ValueError, match="exactly one root link"):
        exported_root_bodies(model, links, 1)
    with pytest.raises(ValueError, match="exactly 3 root links"):
        exported_root_bodies(model, links, 3)


def test_the_matrix_covers_pairs_across_the_two_robots(two_arms):
    """The whole reason for one description: the arms swing into each other's space, and a pair that
    is not in the matrix at all is a pair MoveIt keeps checking rather than one it may ignore."""
    model, links = two_arms
    matrix = {(a, b): r for a, b, r in collision_matrix(model, links, samples=200)}
    assert _reason(matrix, "a_base", "b_base") == "Never"
    # The two long links sweep through the same volume, so they touch in some configurations and not
    # in others -- exactly the pair that must stay checked.
    assert ("a_link", "b_link") not in matrix and ("b_link", "a_link") not in matrix


def test_a_group_per_robot_plus_one_spanning_both(two_arms):
    model, links = two_arms
    tree = build_srdf(
        model,
        links,
        name="pair",
        arms=[
            ArmGroup(name="a", base_link="a_base", tip_link="a_link", home={"a_j": 0.1}),
            ArmGroup(name="b", base_link="b_base", tip_link="b_link", home={"b_j": 0.2}),
        ],
        combined_group="both_arms",
        urdf_root_link="base_link",
        samples=20,
    )
    root = tree.getroot()
    assert [g.get("name") for g in root.findall("group")] == [
        "a",
        "a_gripper",
        "b",
        "b_gripper",
        "both_arms",
    ]
    assert [
        (c.get("base_link"), c.get("tip_link"))
        for c in root.findall("group[@name='both_arms']/chain")
    ] == [("a_base", "a_link"), ("b_base", "b_link")]
    assert {s.get("group") for s in root.findall("group_state[@name='home']")} == {"a", "b"}


def test_a_combined_group_for_a_single_robot_is_refused(two_arms):
    """It exists to plan several chains at once; over one chain it is the arm group under a second
    name, and MoveIt would then have two groups nothing tells apart."""
    model, links = two_arms
    with pytest.raises(ValueError, match="exists to plan several chains"):
        build_srdf(
            model,
            links,
            name="pair",
            arms=[ArmGroup(name="a", base_link="a_base", tip_link="a_link")],
            combined_group="both_arms",
            urdf_root_link="base_link",
            samples=5,
        )


def test_two_groups_of_the_same_name_are_refused(two_arms):
    model, links = two_arms
    with pytest.raises(ValueError, match="called the same thing"):
        build_srdf(
            model,
            links,
            name="pair",
            arms=[
                ArmGroup(name="a", base_link="a_base", tip_link="a_link"),
                ArmGroup(name="a", base_link="b_base", tip_link="b_link"),
            ],
            combined_group="",
            urdf_root_link="base_link",
            samples=5,
        )
